# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.cities_api import CitiesApi  # noqa: E501
from api.rest import ApiException


class TestCitiesApi(unittest.TestCase):
    """CitiesApi unit test stubs"""

    def setUp(self):
        self.api = api.api.cities_api.CitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cities_list(self):
        """Test case for cities_list

        """
        pass

    def test_cities_read(self):
        """Test case for cities_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
