# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.fundcards_public_api import FundcardsPublicApi  # noqa: E501
from api.rest import ApiException


class TestFundcardsPublicApi(unittest.TestCase):
    """FundcardsPublicApi unit test stubs"""

    def setUp(self):
        self.api = api.api.fundcards_public_api.FundcardsPublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fundcards_public_donate(self):
        """Test case for fundcards_public_donate

        """
        pass

    def test_fundcards_public_list(self):
        """Test case for fundcards_public_list

        """
        pass

    def test_fundcards_public_read(self):
        """Test case for fundcards_public_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
