# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.fundcards_api import FundcardsApi  # noqa: E501
from api.rest import ApiException


class TestFundcardsApi(unittest.TestCase):
    """FundcardsApi unit test stubs"""

    def setUp(self):
        self.api = api.api.fundcards_api.FundcardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fundcards_list(self):
        """Test case for fundcards_list

        """
        pass

    def test_fundcards_read(self):
        """Test case for fundcards_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
