# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.fundraising_types_api import FundraisingTypesApi  # noqa: E501
from api.rest import ApiException


class TestFundraisingTypesApi(unittest.TestCase):
    """FundraisingTypesApi unit test stubs"""

    def setUp(self):
        self.api = api.api.fundraising_types_api.FundraisingTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fundraising_types_list(self):
        """Test case for fundraising_types_list

        """
        pass

    def test_fundraising_types_read(self):
        """Test case for fundraising_types_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
