# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.fund_card_donate import FundCardDonate  # noqa: E501
from api.rest import ApiException


class TestFundCardDonate(unittest.TestCase):
    """FundCardDonate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundCardDonate(self):
        """Test FundCardDonate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.fund_card_donate.FundCardDonate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
