# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.feedback_theme import FeedbackTheme  # noqa: E501
from api.rest import ApiException


class TestFeedbackTheme(unittest.TestCase):
    """FeedbackTheme unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeedbackTheme(self):
        """Test FeedbackTheme"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.feedback_theme.FeedbackTheme()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
