# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.organizations_api import OrganizationsApi  # noqa: E501
from api.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = api.api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_organizations_list(self):
        """Test case for organizations_list

        """
        pass

    def test_organizations_read(self):
        """Test case for organizations_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
