# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.password_reset_confirm import PasswordResetConfirm  # noqa: E501
from api.rest import ApiException


class TestPasswordResetConfirm(unittest.TestCase):
    """PasswordResetConfirm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPasswordResetConfirm(self):
        """Test PasswordResetConfirm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.password_reset_confirm.PasswordResetConfirm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
