# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.countries_api import CountriesApi  # noqa: E501
from api.rest import ApiException


class TestCountriesApi(unittest.TestCase):
    """CountriesApi unit test stubs"""

    def setUp(self):
        self.api = api.api.countries_api.CountriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_countries_list(self):
        """Test case for countries_list

        """
        pass

    def test_countries_read(self):
        """Test case for countries_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
