# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.api.accounts_api import AccountsApi  # noqa: E501
from api.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = api.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_login(self):
        """Test case for accounts_login

        """
        pass

    def test_accounts_password_reset(self):
        """Test case for accounts_password_reset

        """
        pass

    def test_accounts_password_reset_confirm(self):
        """Test case for accounts_password_reset_confirm

        """
        pass

    def test_accounts_registration(self):
        """Test case for accounts_registration

        """
        pass

    def test_accounts_send_verify_email(self):
        """Test case for accounts_send_verify_email

        """
        pass

    def test_accounts_verify_email(self):
        """Test case for accounts_verify_email

        """
        pass


if __name__ == '__main__':
    unittest.main()
