# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import veros_api
from veros_api.models.card_go import CardGo  # noqa: E501
from veros_api.rest import ApiException


class TestCardGo(unittest.TestCase):
    """CardGo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardGo(self):
        """Test CardGo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = veros_api.models.card_go.CardGo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
