# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.direction import Direction  # noqa: E501
from api.rest import ApiException


class TestDirection(unittest.TestCase):
    """Direction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirection(self):
        """Test Direction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.direction.Direction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
