# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import veros_api
from veros_api.models.organizer import Organizer  # noqa: E501
from veros_api.rest import ApiException


class TestOrganizer(unittest.TestCase):
    """Organizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizer(self):
        """Test Organizer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = veros_api.models.organizer.Organizer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
