# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.json_web_token import JSONWebToken  # noqa: E501
from api.rest import ApiException


class TestJSONWebToken(unittest.TestCase):
    """JSONWebToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJSONWebToken(self):
        """Test JSONWebToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.json_web_token.JSONWebToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
