# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.country import Country  # noqa: E501
from api.rest import ApiException


class TestCountry(unittest.TestCase):
    """Country unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountry(self):
        """Test Country"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.country.Country()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
