# coding: utf-8

"""
    Veros API

    Routes of Veros project  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api
from api.models.bad_request_response import BadRequestResponse  # noqa: E501
from api.rest import ApiException


class TestBadRequestResponse(unittest.TestCase):
    """BadRequestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequestResponse(self):
        """Test BadRequestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api.models.bad_request_response.BadRequestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
